routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'PagesController@index')->name('index');

Auth::routes();

Route::post('/investments/invest/{id}', function (Request $request, $id) {
    try {
        \Mail::send(new \App\Mail\ProjectMail($request, $id, "reply"));
    } catch (Exception $err) {
    }
    return redirect('/')->with('toast_success', 'Thanks! Email sent to owner!');
})->name('invest');

Route::get('/investments', 'PagesController@investments')->name('investments');
Route::get('/investments/search', 'PagesController@search')->name('search');
Route::get('/investments/filter', 'PagesController@searchFilter')->name('filter');
Route::get('/investments/category/{category}', 'PagesController@searchCategory')->name('category');
Route::get('/investments/cities/{id}', 'PagesController@getCities')->name('cities');
Route::get('/investments/{id}', 'PagesController@details')->name('investments.show');
Route::get('/services', 'PagesController@services')->name('services');
Route::get('/services/details/{name}', 'PagesController@servicesDetails')->name('services-details');
Route::get('/about', 'PagesController@about')->name('about');
Route::get('/postproject', 'PagesController@postproject')->name('post');
Route::get('/help/show-more', 'PagesController@showMore')->name('help.showMore');
Route::get('/blog/{id}', 'PagesController@showblog')->name('blog.showblog');
Route::get('/help/searchblog', 'PagesController@searchblog')->name("searchblog");
Route::get('/help', 'PagesController@help')->name('help');
Route::get('/help/contact', 'PagesController@contact')->name('contact');
Route::get('/blog', 'PagesController@blog')->name('blog');
Route::post('/help/subscribe', 'MailChimpController@subscribe')->name('subscribe');

Route::resource('categories', 'CategoryController');
Route::resource('projects', 'ProjectController');
Route::get('/projects/image/{filename}', 'ProjectController@renderImage')->name('projects.image');
Route::post('/projects/store', 'ProjectController@store')->name('projects.store');

Route::get('blogs/image/{filename}', 'Admin\BlogController@renderImage')->name('posts.image');
Route::get('team/image/{filename}', 'Admin\TeamController@renderImage')->name('users.image');

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('login', 'Admin\Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Admin\Auth\LoginController@login')->name('login');

    Route::group(['middleware' => 'admin'], function () {
        Route::get('/', function () {
            return redirect()->route('admin.dashboard');
        });
        Route::get('dashboard', 'Admin\DashboardController@getDashboard')->name('dashboard');

        Route::resource('categories', 'Admin\CategoryController');

        Route::resource('countries', 'Admin\CountryController');
        Route::resource('team', 'Admin\TeamController');
        Route::resource('cities', 'Admin\CityController');
        Route::resource('faqs', 'Admin\FAQController');
        Route::PATCH('categories/{category}/restore', 'Admin\CategoryController@restore')->name('categories.restore');
        Route::PATCH('countries/{country}/restore', 'Admin\CountryController@restore')->name('countries.restore');

        Route::resource('blogs', 'Admin\BlogController');

        Route::resource('projects', 'Admin\ProjectController');
        Route::any('projects/{id}/{appraisal}', function ($id, $appraisal) {
            try {
                \Mail::send(new \App\Mail\ProjectMail(null, $id, $appraisal));
            } catch (Exception $err) {
            }
            return redirect('admin');
        })->name('appraisalMail');

        // PROFILE
        Route::get('/profile', 'Admin\ProfileController@getProfile')->name('profile');
        Route::post('/profile/edit', 'Admin\ProfileController@editProfile')->name('profile.edit');
        Route::post('/settings/edit', 'Admin\ProfileController@editSiteSettings')->name('settings.edit');
        Route::post('/profile/change-password', 'Admin\ProfileController@changePassword')->name('profile.password');

        Route::get('logout', 'Admin\Auth\LoginController@logout')->name('logout');
    });
});

resources/views/admin/_blank.blade.php
@extends('admin.layouts.app')
@section('title', 'Page Title')

@section('content')
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Prev Page</a></li>
                        <li class="breadcrumb-item active">Page Title</li>
                    </ol>
                </div>
                <h4 class="page-title">Page Title</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->


@endsection

@section('footer_script')
    <script></script>
@endsection

resources/views/admin/dashboard.blade.php
@extends('admin.layouts.app')
@section('title', 'Dashboard')

@section('content')
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Icons</a></li>
                        <li class="breadcrumb-item active">Feather</li>
                    </ol>
                </div>
                <h4 class="page-title">Dashboard</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-md-6 col-xl-3">
            <a href="{{ route('admin.projects.index') }}">
                <div class="widget-rounded-circle card-box">
                    <div class="row">
                        <div class="col-6">
                            <div class="avatar-lg rounded-circle bg-soft-success border-success border">
                                <i class="fe-shopping-cart font-22 avatar-title text-success"></i>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="text-right">
                                <h3 class="text-dark mt-1"><span
                                            data-plugin="counterup">{{ \App\Project::count() }}</span></h3>
                                <p class="text-muted mb-1 text-truncate">Total Projects</p>
                            </div>
                        </div>
                    </div> <!-- end row-->
                </div> <!-- end widget-rounded-circle-->
            </a>
        </div> <!-- end col-->

        <div class="col-md-6 col-xl-3">
            <a href="{{ route('admin.projects.index', ['status' => 'pending']) }}">
                <div class="widget-rounded-circle card-box">
                    <div class="row">
                        <div class="col-6">
                            <div class="avatar-lg rounded-circle bg-soft-primary border-primary border">
                                <i class="fe-heart font-22 avatar-title text-primary"></i>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="text-right">
                                <h3 class="mt-1"><span
                                            data-plugin="counterup">{{ \App\Project::where('status', 'pending')->count() }}</span>
                                </h3>
                                <p class="text-muted mb-1 text-truncate">Pending Review</p>
                            </div>
                        </div>
                    </div> <!-- end row-->
                </div> <!-- end widget-rounded-circle-->
            </a>
        </div> <!-- end col-->

        <div class="col-md-6 col-xl-3">
            <a href="{{ route('admin.projects.index', ['status' => 'approved']) }}">
                <div class="widget-rounded-circle card-box">
                    <div class="row">
                        <div class="col-6">
                            <div class="avatar-lg rounded-circle bg-soft-warning border-warning border">
                                <i class="fe-eye font-22 avatar-title text-warning"></i>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="text-right">
                                <h3 class="text-dark mt-1"><span
                                            data-plugin="counterup">{{ \App\Project::where('status', 'approved')->count() }}</span>
                                </h3>
                                <p class="text-muted mb-1 text-truncate">Active Projects</p>
                            </div>
                        </div>
                    </div> <!-- end row-->
                </div> <!-- end widget-rounded-circle-->
            </a>
        </div> <!-- end col-->

        <div class="col-md-6 col-xl-3">
            <a href="{{ route('admin.categories.index') }}">
                <div class="widget-rounded-circle card-box">
                    <div class="row">
                        <div class="col-6">
                            <div class="avatar-lg rounded-circle bg-soft-info border-info border">
                                <i class="fe-bar-chart-line- font-22 avatar-title text-info"></i>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="text-right">
                                <h3 class="text-dark mt-1"><span
                                            data-plugin="counterup">{{ \App\Category::where('voided', false)->count() }}</span>
                                </h3>
                                <p class="text-muted mb-1 text-truncate">Active Categories</p>
                            </div>
                        </div>
                    </div> <!-- end row-->
                </div> <!-- end widget-rounded-circle-->
            </a>
        </div> <!-- end col-->


    </div>
    <!-- end row-->

@endsection

@section('footer_script')
    <script></script>
@endsection

resources/views/admin/profile.blade.php
@extends('admin.layouts.app')
@section('title', 'Edit Settings')

@section('content')
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Dashboard</a></li>
                        <li class="breadcrumb-item active">Edit Settings</li>
                    </ol>
                </div>
                <h4 class="page-title">Edit Settings</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->


    <div class="row">
        <div class="col-sm-6">

            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Site Settings</h4>
                    <form method="post" action="{{ route('admin.settings.edit') }}">
                        @csrf

                        <div class="form-group">
                            <label>Site Name <em>*</em></label>
                            <input type="text"
                                   name="site_name" value="{{ old('site_name', $setting[0]->site_name) }}"
                                   class="form-control {{ $errors->has('site_name') ? ' is-invalid' : '' }}"
                                   placeholder="Site Name" required="">

                            @if ($errors->has('site_name'))
                                <span class="invalid-feedback">
                                    <strong>{{ $errors->first('site_name') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label>Site Email <em>*</em></label>
                            <input type="email" value="{{ old('site_email', $setting[0]->site_email) }}"
                                   class="form-control {{ $errors->has('site_email') ? ' is-invalid' : '' }}" name="site_email"
                                   placeholder="Email" required >

                            @if ($errors->has('site_email'))
                                <span class="invalid-feedback">
                                    <strong>{{ $errors->first('site_email') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group text-right">
                            <button class="btn btn-primary" type="submit">Update</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Change Password</h4>
                    <form method="post" action="{{ route('admin.profile.password') }}">
                        @csrf

                        <div class="form-group">
                            <label>Current Password <em>*</em></label>
                            <input type="password"
                                   class="form-control {{ $errors->has('current_password') ? "is-invalid" : "" }}"
                                   name="current_password">

                            @if ($errors->has('current_password'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('current_password') }}
                                </div>
                            @endif
                        </div>

                        <!-- New Password -->
                        <div class="form-group">
                            <label>{{ __('New Password') }} <em>*</em></label>
                            <input type="password"
                                   class="form-control {{ $errors->has('password') ? "is-invalid" : "" }}"
                                   name="password">

                            @if ($errors->has('password'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('password') }}
                                </div>
                            @endif
                        </div>

                        <!-- Retype New Password -->
                        <div class="form-group">

                            <label>{{ __('Retype New Password') }} <em>*</em></label>

                            <input type="password" class="form-control"
                                   name="password_confirmation">

                        </div>

                        <div class="form-group text-right">
                            <button class="btn btn-primary" type="submit">Change Password</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>

        <div class="col-sm-6">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Basic Info</h4>
                    <form method="post" action="{{ route('admin.profile.edit') }}">
                        @csrf

                        <div class="form-group">
                            <label>Name <em>*</em></label>
                            <input type="text"
                                   name="name" value="{{ old('name', $user->name) }}"
                                   class="form-control {{ $errors->has('name') ? ' is-invalid' : '' }}"
                                   placeholder="Name" required="">

                            @if ($errors->has('name'))
                                <span class="invalid-feedback">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label>Email</label>
                            <input type="email" value="{{ $user->email }}"
                                   class="form-control"
                                   placeholder="Email" readonly>

                        </div>

                        <div class="form-group text-right">
                            <button class="btn btn-primary" type="submit">Update</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>

@endsection

@section('footer_script')
    <script></script>
@endsection