routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'PagesController@index')->name('index');

Auth::routes();

Route::post('/investments/invest/{id}', function (Request $request, $id) {
    try {
        \Mail::send(new \App\Mail\ProjectMail($request, $id, "reply"));
    } catch (Exception $err) {
    }
    return redirect('/')->with('toast_success', 'Thanks! Email sent to owner!');
})->name('invest');

Route::get('/investments', 'PagesController@investments')->name('investments');
Route::get('/investments/search', 'PagesController@search')->name('search');
Route::get('/investments/filter', 'PagesController@searchFilter')->name('filter');
Route::get('/investments/category/{category}', 'PagesController@searchCategory')->name('category');
Route::get('/investments/cities/{id}', 'PagesController@getCities')->name('cities');
Route::get('/investments/{id}', 'PagesController@details')->name('investments.show');
Route::get('/services', 'PagesController@services')->name('services');
Route::get('/services/details/{name}', 'PagesController@servicesDetails')->name('services-details');
Route::get('/about', 'PagesController@about')->name('about');
Route::get('/postproject', 'PagesController@postproject')->name('post');
Route::get('/help/show-more', 'PagesController@showMore')->name('help.showMore');
Route::get('/blog/{id}', 'PagesController@showblog')->name('blog.showblog');
Route::get('/help/searchblog', 'PagesController@searchblog')->name("searchblog");
Route::get('/help', 'PagesController@help')->name('help');
Route::get('/help/contact', 'PagesController@contact')->name('contact');
Route::get('/blog', 'PagesController@blog')->name('blog');
Route::post('/help/subscribe', 'MailChimpController@subscribe')->name('subscribe');

Route::resource('categories', 'CategoryController');
Route::resource('projects', 'ProjectController');
Route::get('/projects/image/{filename}', 'ProjectController@renderImage')->name('projects.image');
Route::post('/projects/store', 'ProjectController@store')->name('projects.store');

Route::get('blogs/image/{filename}', 'Admin\BlogController@renderImage')->name('posts.image');
Route::get('team/image/{filename}', 'Admin\TeamController@renderImage')->name('users.image');

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('login', 'Admin\Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Admin\Auth\LoginController@login')->name('login');

    Route::group(['middleware' => 'admin'], function () {
        Route::get('/', function () {
            return redirect()->route('admin.dashboard');
        });
        Route::get('dashboard', 'Admin\DashboardController@getDashboard')->name('dashboard');

        Route::resource('categories', 'Admin\CategoryController');

        Route::resource('countries', 'Admin\CountryController');
        Route::resource('team', 'Admin\TeamController');
        Route::resource('cities', 'Admin\CityController');
        Route::resource('faqs', 'Admin\FAQController');
        Route::PATCH('categories/{category}/restore', 'Admin\CategoryController@restore')->name('categories.restore');
        Route::PATCH('countries/{country}/restore', 'Admin\CountryController@restore')->name('countries.restore');

        Route::resource('blogs', 'Admin\BlogController');

        Route::resource('projects', 'Admin\ProjectController');
        Route::any('projects/{id}/{appraisal}', function ($id, $appraisal) {
            try {
                \Mail::send(new \App\Mail\ProjectMail(null, $id, $appraisal));
            } catch (Exception $err) {
            }
            return redirect('admin');
        })->name('appraisalMail');

        // PROFILE
        Route::get('/profile', 'Admin\ProfileController@getProfile')->name('profile');
        Route::post('/profile/edit', 'Admin\ProfileController@editProfile')->name('profile.edit');
        Route::post('/settings/edit', 'Admin\ProfileController@editSiteSettings')->name('settings.edit');
        Route::post('/profile/change-password', 'Admin\ProfileController@changePassword')->name('profile.password');

        Route::get('logout', 'Admin\Auth\LoginController@logout')->name('logout');
    });
});

app/Http/Controllers/Admin/TeamController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Member;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;

class TeamController extends Controller
{
    protected $search = [
        'q' => null,
        'position' => null,
        'sort' => null,
    ];
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $this->search;
        $members = new Member();

        if ($request->get('q')) {
            $search['q'] = $request->get('q');
            $members = $members->where('name', 'like', '%' . $search['q'] . '%');
        }

        if ($request->get('position')) {
            $search['position'] = $request->get('position');
            $members = $members->where('id', $search['position']);
        }

        if ($request->get('sort')) {
            $sort = $request->get('sort');
            switch ($sort) {
                case 'name_asc':
                    $members = $members->orderBy('name', 'ASC');
                    break;

                case 'name_desc':
                    $members = $members->orderBy('name', 'DESC');
                    break;

                case 'newest':
                    $members = $members->orderBy('created_at', 'DESC');
                    break;

                case 'oldest':
                    $members = $members->orderBy('created_at', 'ASC');
                    break;
            }
            $search['sort'] = $sort;
        }

        $members = $members->get();
        $sort_list = [
            'newest' => 'Newest',
            'oldest' => 'Oldest',
            'name_asc' => 'Name (A - Z)',
            'name_desc' => 'Name (Z - A)',
        ];

        return view('admin.team.index', compact('members', 'search', 'sort_list'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.team.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required|unique:members,name',
            'email' => 'required|unique:members,email',
            'position' => 'required',
            'image' => 'image|nullable|max:1999',
            'description' => 'required',
        ]);

        $member = new Member();
        $member->name = $request->name;
        $member->email = $request->email;
        $member->position = $request->position;
        $member->picture = $this->getImageInfo($request);
        $member->description = $request->description;
        $member->save();

        return redirect()->route('admin.team.index')
            ->with('success', 'Member added successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $member = Member::findOrFail($id);
        return view('admin.team.show', compact('member'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $member = Member::findOrFail($id);
        return view('admin.team.edit', compact('member'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $member = Member::findOrFail($id);

        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'email' => 'required',
            'position' => 'required',
            'image' => 'image|nullable|max:1999',
            'description' => 'nullable',
        ]);

        // Check to see if another member already exist with the same name but different id
        $validator->after(function ($validator) use ($request, $member) {
            $existing_title = Member::where('name', $request->title)->first();
            if ($existing_title && $existing_title->id != $member->id) {
                $validator->errors()->add('name', __('This name has already been taken'));
            }
        });

        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }

        $member->name = $request->name;
        $member->email = $request->email;
        $member->position = $request->position;
        if ($request->has('image')) {
            $member->picture = $this->getImageInfo($request);
        }

        $member->description = $request->description;
        $member->save();

        return redirect()->route('admin.team.index')
            ->with('success', 'Team member updated successfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $member = Member::findOrFail($id);

        // unlink(storage_path('app/public/uploads/users/' . $member->member_image));

        $member->delete();

        return redirect()->route('admin.team.index')->with('success', 'Team member deleted successfully');

    }

    private function getImageInfo(Request $request)
    {
        // handle the file upload

        $fileNameToStore = '';
        if ($request->hasFile('image')) {
            // get the file name with extension
            $fileNameWithExt = $request->file('image')->getClientOriginalName();
            // get the filename
            $fileName = pathInfo($fileNameWithExt, PATHINFO_FILENAME);
            // get the extension
            $extension = $request->file('image')->getClientOriginalExtension();
            // filename to store
            $fileNameToStore = Str::slug($fileName . '_' . time()) . '.' . $extension;
            // upload image

            $request->file('image')->storeAs('public/uploads/users', $fileNameToStore);
        }

        return $fileNameToStore;
    }

    public function renderImage($filename)
    {
        $path = storage_path('app/public/uploads/users/' . $filename);

        //if (!\File::exists($path)) abort(404);
        $file = \File::get($path);
        $type = \File::mimeType($path);
        $response = \Response::make($file, 200);
        $response->header('Content-Type', $type);
        return $response;
    }
}

resources/views/admin/team/create.blade.php
@extends('admin.layouts.app')
@section('title', 'New Member')

@section('header-style')
    <style>
        .summernote {
            background: transparent;
            -webkit-box-shadow: none;
            box-shadow: none;
        }
        .summernote .btn {
            color: rgba(0, 0, 0, .54)!important;
            background-color: transparent!important;
            padding: 6px 12px;
            font-size: 14px;
            line-height: 1.42857;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
            -webkit-box-shadow: none;
            box-shadow: none;
        }
        .summernote {
            vertical-align: middle;
        }
    </style>
@endsection

@section('content')
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('admin.team.index') }}">Team</a></li>
                        {{-- <li class="breadcrumb-item active">{{ $member->name }}</li> --}}
                    </ol>
                </div>
                <h4 class="page-title">New Team Member</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">New Team Member</h5>
            <form method="POST" action="{{ route('admin.team.store') }}" enctype="multipart/form-data">
                @csrf

                <div class="form-group">
                    <label>Name <em>*</em></label>
                    <input type="text" name="name"
                           value="{{ old('name') }}"
                           class="form-control @error('name') is-invalid @enderror">
                    @error('name')
                    <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>

                <div class="form-group">
                    <label>E-mail <em>*</em></label>
                    <input type="text" name="email"
                           value="{{ old('email') }}"
                           class="form-control @error('email') is-invalid @enderror">
                    @error('email')
                    <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>

                <div class="form-group">
                    <label>Role <em>*</em></label>
                    <input type="text" name="position"
                           value="{{ old('position') }}"
                           class="form-control @error('position') is-invalid @enderror">
                    @error('position')
                        <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>

                 <div class="form-group">
                    <label>Image</label>
                    <input type="file" name="image"
                           value="{{ old('image') }}"
                           class="form-control @error('image') is-invalid @enderror">
                    @error('image')
                    <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>

                <div class="form-group summernote">
                    <label>Description</label>
                    <textarea id="member-summernote" class="form-control @error('description') is-invalid @enderror" name="description" rows="5">{{ old('description') }}</textarea>
                    @error('description')
                    <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>

                <div class="text-right">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>

            </form>
        </div>
    </div>

@endsection

@section('footer_script')
    <script>
        $('#member-summernote').summernote({
            minHeight: 200,
            placeholder: 'Write here ...',
            focus: false,
            airMode: false,
            fontNames: ['Roboto', 'Calibri', 'Times New Roman', 'Arial'],
            fontNamesIgnoreCheck: ['Roboto', 'Calibri'],
            dialogsInBody: true,
            dialogsFade: true,
            disableDragAndDrop: false,
            toolbar: [
                // [groupName, [list of button]]
                ['style', ['bold', 'italic', 'underline', 'clear']],
                ['para', ['style', 'ul', 'ol', 'paragraph']],
                ['fontsize', ['fontsize']],
                ['font', ['strikethrough', 'superscript', 'subscript']],
                ['height', ['height']],
                ['misc', ['undo', 'redo', 'print', 'help', 'fullscreen']]
            ],
            popover: {
                air: [
                ['color', ['color']],
                ['font', ['bold', 'underline', 'clear']]
                ]
            },
            print: {
                //'stylesheetUrl': 'url_of_stylesheet_for_printing'
            }
        });
        $("#image").on('change', () => {
            var image = $("input#image").val()
            $("label#filename").text(basename(image, "\\"))
        })

        function basename(str, sep) {
            return str.substr(str.lastIndexOf(sep) + 1);
        }
    </script>
@endsection

resources/views/admin/team/edit.blade.php
@extends('admin.layouts.app')
@section('title', $member->name)

@section('header-style')
    <style>
        .summernote {
            background: transparent;
            -webkit-box-shadow: none;
            box-shadow: none;
        }
        .summernote .btn {
            color: rgba(0, 0, 0, .54)!important;
            background-color: transparent!important;
            padding: 6px 12px;
            font-size: 14px;
            line-height: 1.42857;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
            -webkit-box-shadow: none;
            box-shadow: none;
        }
        .summernote {
            vertical-align: middle;
        }
    </style>
@endsection

@section('content')
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('admin.team.index') }}">Team</a></li>
                        <li class="breadcrumb-item active">{{ $member->name }}</li>
                    </ol>
                </div>
                <h4 class="page-title">Edit: {{ $member->name }}</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Edit Post</h5>
            <form method="POST" action="{{ route('admin.team.update', $member->id) }}" enctype="multipart/form-data">
                @csrf
                @method('PATCH')

                <div class="form-group">
                    <label>Name <em>*</em></label>
                    <input type="text" name="name"
                           value="{{ old('name', $member->name) }}"
                           class="form-control @error('name') is-invalid @enderror">
                    @error('name')
                    <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>

                <div class="form-group">
                    <label>E-mail <em>*</em></label>
                    <input type="text" name="email"
                           value="{{ old('email', $member->email) }}"
                           class="form-control @error('email') is-invalid @enderror">
                    @error('email')
                    <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>

                <div class="form-group">
                    <label>Role <em>*</em></label>
                    <input type="text" name="position"
                           value="{{ old('position', $member->position) }}"
                           class="form-control @error('position') is-invalid @enderror">
                    @error('position')
                        <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>

                <div class="form-group">
                    <label>Image</label>

                    <div class="form-control">
                        <input id="image" type="file" name="image" class="hidden @error('image') is-invalid @enderror" style="width: 6.5em;">
                        <label id="filename" for="image">{{ request()->image ? basename(request()->image) : basename($member->getImageURL()) }}</label>
                    </div>

                    @error('image')
                        <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>

                <div class="form-group summernote">
                    <label>Description</label>
                    <textarea id="member-summernote" class="form-control @error('description') is-invalid @enderror" name="description" rows="5">{{ old('description', $member->description) }}</textarea>
                    @error('description')
                    <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>

                <div class="text-right">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>

            </form>
        </div>
    </div>

@endsection

@section('footer_script')
    <script>
        $('#member-summernote').summernote({
            minHeight: 200,
            placeholder: 'Write here ...',
            focus: false,
            airMode: false,
            fontNames: ['Roboto', 'Calibri', 'Times New Roman', 'Arial'],
            fontNamesIgnoreCheck: ['Roboto', 'Calibri'],
            dialogsInBody: true,
            dialogsFade: true,
            disableDragAndDrop: false,
            toolbar: [
                // [groupName, [list of button]]
                ['style', ['bold', 'italic', 'underline', 'clear']],
                ['para', ['style', 'ul', 'ol', 'paragraph']],
                ['fontsize', ['fontsize']],
                ['font', ['strikethrough', 'superscript', 'subscript']],
                ['height', ['height']],
                ['misc', ['undo', 'redo', 'print', 'help', 'fullscreen']]
            ],
            popover: {
                air: [
                ['color', ['color']],
                ['font', ['bold', 'underline', 'clear']]
                ]
            },
            print: {
                //'stylesheetUrl': 'url_of_stylesheet_for_printing'
            }
        });
        $("#image").on('change', () => {
            var image = $("input#image").val()
            $("label#filename").text(basename(image, "\\"))
        })

        function basename(str, sep) {
            return str.substr(str.lastIndexOf(sep) + 1);
        }
    </script>
@endsection

resources/views/admin/team/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Team')

@section('content')
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Dashboard</a></li>
                        <li class="breadcrumb-item active">Team</li>
                    </ol>
                </div>
                <h4 class="page-title"> Team</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    {{-- Filter Section --}}
    <div class="row">
        <div class="col-12">
            <div class="card-box">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="{{ $search['q'] || $search['position'] ? 'show' : '' }}" id="collapseFilter" style="">
                            <form class="form-inline" accept="{{ route('admin.team.index') }}">
                                <div class="form-group">
                                    <label for="inputPassword2" class="sr-only">Search</label>
                                    <input type="search" class="form-control" name="q" value="{{ $search['q'] }}" id="inputPassword2" placeholder="Search...">
                                </div>
                                <div class="form-group mx-sm-3">
                                    <select class="form-control" name="sort">
                                        <option value="">--Sort--</option>
                                        @foreach($sort_list as $sort => $name)
                                            <option value="{{ $sort }}"
                                                    @if($sort === $search['sort']) selected @endif>
                                                {!! $name !!}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group mr-sm-3">
                                    <select class="form-control" id="position" name="position">
                                        <option value="">--Position--</option>
                                        @foreach(\App\Member::orderBy('position', 'ASC')->get() as $member)
                                            <option value="{{ $member->id }}"
                                                    @if($member->id == $search['position']) selected @endif>
                                                {{ $member->position }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group mr-sm-3 ">
                                    <button type="submit" class="btn btn-light btn-block"><i class="fa fa-search"></i> Search
                                    </button>
                                </div>
                            </form>
                        </div>

                    </div>
                    <div class="col-lg-4">
                        <div class="text-lg-right mt-3 mt-lg-0">
                            <a href="{{ route('admin.team.create') }}" class="btn btn-primary waves-effect waves-light"><i class="mdi mdi-plus-circle mr-1"></i> Add New</a>
                        </div>
                    </div><!-- end col-->
                </div> <!-- end row -->
            </div> <!-- end card-box -->
        </div><!-- end col-->
    </div>

    <div class="row">
        @foreach($members as $member)
            <div class="col-lg-4">
                <div class="text-center card-box">
                    <div class="pt-2 pb-2">
                        <a href="{{ route('admin.team.show', $member->id) }}">
                            <img src="{{ $member->getImageURL() }}" class="rounded-circle img-thumbnail avatar-xl" alt="profile-image">
                        </a>

                        <h4 class="mt-3"><a href="{{ route('admin.team.show', $member->id) }}" class="text-dark">{{ $member->name }}</a></h4>
                        <h6>{{ $member->email }}</h6>

                        <p class="text-muted lead">@ {!! $member->position !!}</p>

                        <div class="d-flex justify-content-center">
                            <a href="{{ route('admin.team.edit', $member->id) }}" class="btn btn-success btn-sm waves-effect waves-light">Edit</a>
                         <form method="POST" action="{{ route('admin.team.destroy', $member->id) }}">
                            @method('DELETE')
                            @csrf
                            <button style="margin-left:3px" type="submit" class="btn btn-danger btn-sm waves-effect">Delete</button>
                         </form>
                        </div>

                        <p class="card-text py-4">{{ $member->getShortDesc() }}</p>

                    </div> <!-- end .padding -->
                </div> <!-- end card-box-->
            </div> <!-- end col -->
        @endforeach
    </div>
@endsection

resources/views/admin/team/show.blade.php
@extends('admin.layouts.app')
@section('title', $member->name)

@section('content')
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('admin.team.index') }}">Team</a></li>
                        <li class="breadcrumb-item active">{{ $member->name }}</li>
                    </ol>
                </div>
                <h4 class="page-title">Team member Detail</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row flex-column-reverse flex-md-row">
        <div class="col-md-7">
            <div class="card d-block">
                <div class="card-body">
                    <!-- member title-->
                    <h3 class="mt-0 font-20">
                        {{ $member->name }}
                    </h3>

                    <p class="my-3 text-muted">
                        {!! $member->description !!}
                    </p>

                </div> <!-- end card-body-->

            </div>
        </div>
        <div class="col-md-5">

            <div class="card d-block text-center p-3">
                <img src="{{ $member->getImageURL() }} " class="img-fluid rounded-circle img-thumbnail avatar-xl">
                <div class="card-text my-3">
                    <h3>{{ $member->position }}</h3>
                    <h5>{{ $member->email }}</h5>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('footer_script')
    <script></script>
@endsection