routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'PagesController@index')->name('index');

Auth::routes();

Route::post('/investments/invest/{id}', function (Request $request, $id) {
    try {
        \Mail::send(new \App\Mail\ProjectMail($request, $id, "reply"));
    } catch (Exception $err) {
    }
    return redirect('/')->with('toast_success', 'Thanks! Email sent to owner!');
})->name('invest');

Route::get('/investments', 'PagesController@investments')->name('investments');
Route::get('/investments/search', 'PagesController@search')->name('search');
Route::get('/investments/filter', 'PagesController@searchFilter')->name('filter');
Route::get('/investments/category/{category}', 'PagesController@searchCategory')->name('category');
Route::get('/investments/cities/{id}', 'PagesController@getCities')->name('cities');
Route::get('/investments/{id}', 'PagesController@details')->name('investments.show');
Route::get('/services', 'PagesController@services')->name('services');
Route::get('/services/details/{name}', 'PagesController@servicesDetails')->name('services-details');
Route::get('/about', 'PagesController@about')->name('about');
Route::get('/postproject', 'PagesController@postproject')->name('post');
Route::get('/help/show-more', 'PagesController@showMore')->name('help.showMore');
Route::get('/blog/{id}', 'PagesController@showblog')->name('blog.showblog');
Route::get('/help/searchblog', 'PagesController@searchblog')->name("searchblog");
Route::get('/help', 'PagesController@help')->name('help');
Route::get('/help/contact', 'PagesController@contact')->name('contact');
Route::get('/blog', 'PagesController@blog')->name('blog');
Route::post('/help/subscribe', 'MailChimpController@subscribe')->name('subscribe');

Route::resource('categories', 'CategoryController');
Route::resource('projects', 'ProjectController');
Route::get('/projects/image/{filename}', 'ProjectController@renderImage')->name('projects.image');
Route::post('/projects/store', 'ProjectController@store')->name('projects.store');

Route::get('blogs/image/{filename}', 'Admin\BlogController@renderImage')->name('posts.image');
Route::get('team/image/{filename}', 'Admin\TeamController@renderImage')->name('users.image');

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('login', 'Admin\Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Admin\Auth\LoginController@login')->name('login');

    Route::group(['middleware' => 'admin'], function () {
        Route::get('/', function () {
            return redirect()->route('admin.dashboard');
        });
        Route::get('dashboard', 'Admin\DashboardController@getDashboard')->name('dashboard');

        Route::resource('categories', 'Admin\CategoryController');

        Route::resource('countries', 'Admin\CountryController');
        Route::resource('team', 'Admin\TeamController');
        Route::resource('cities', 'Admin\CityController');
        Route::resource('faqs', 'Admin\FAQController');
        Route::PATCH('categories/{category}/restore', 'Admin\CategoryController@restore')->name('categories.restore');
        Route::PATCH('countries/{country}/restore', 'Admin\CountryController@restore')->name('countries.restore');

        Route::resource('blogs', 'Admin\BlogController');

        Route::resource('projects', 'Admin\ProjectController');
        Route::any('projects/{id}/{appraisal}', function ($id, $appraisal) {
            try {
                \Mail::send(new \App\Mail\ProjectMail(null, $id, $appraisal));
            } catch (Exception $err) {
            }
            return redirect('admin');
        })->name('appraisalMail');

        // PROFILE
        Route::get('/profile', 'Admin\ProfileController@getProfile')->name('profile');
        Route::post('/profile/edit', 'Admin\ProfileController@editProfile')->name('profile.edit');
        Route::post('/settings/edit', 'Admin\ProfileController@editSiteSettings')->name('settings.edit');
        Route::post('/profile/change-password', 'Admin\ProfileController@changePassword')->name('profile.password');

        Route::get('logout', 'Admin\Auth\LoginController@logout')->name('logout');
    });
});

resources/views/admin/layouts/alerts.blade.php
@if(session()->get('warning'))
    <div class="alert alert-warning alert-dismissible fade show mt-3" role="alert">
        {{ session()->get('warning') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

@if(session()->get('info'))
    <div class="alert alert-info alert-dismissible fade show mt-3" role="alert">
        {{ session()->get('info') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

@if(session()->get('error'))
    <div class="alert alert-danger alert-dismissible fade show mt-3" role="alert">
        {{ session()->get('error') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

@if(session()->get('success'))
    <div class="alert alert-success alert-dismissible fade show mt-3" role="alert">
        {{ session()->get('success') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8"/>
    <title>@yield('title') | Back-office Administrateur | Mohada</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <!-- App favicon -->
    <link rel="shortcut icon" href="{{ asset('admin_assets/images/favicon.png') }}">

    <!-- Plugins css -->
    <link href="{{ asset('admin_assets/libs/selectize/css/selectize.bootstrap3.css') }}" rel="stylesheet"/>

    <!-- App css -->
    <link href="{{ asset('admin_assets/css/summernote-bs4.css') }}" rel="stylesheet">
    <link href="{{ asset('admin_assets/css/bootstrap.min.css') }}" rel="stylesheet"/>
    <link href="{{ asset('admin_assets/css/app.min.css') }}" rel="stylesheet"/>
    <link href="{{ asset('admin_assets/css/user.css') }}" rel="stylesheet"/>

    <!-- icons -->
    <link href="{{ asset('admin_assets/css/icons.min.css') }}" rel="stylesheet" type="text/css"/>

    @yield('header-style')
</head>

<body data-layout='{"mode": "light", "width": "fluid", "menuPosition": "fixed", "sidebar": { "color": "light", "size": "default", "showuser": false}, "topbar": {"color": "dark"}, "showRightSidebarOnPageLoad": true}'>

<!-- Begin page -->
<div id="wrapper">

    <!-- Topbar Start -->
@include('admin.layouts.header')
<!-- end Topbar -->


    <!-- ========== Left Sidebar Start ========== -->
@include('admin.layouts.sidebar')
<!-- Left Sidebar End -->


    <!-- ============================================================== -->
    <!-- Start Page Content here -->
    <!-- ============================================================== -->

    <div class="content-page">
        <div class="content">

            <!-- Start Content-->
            <div class="container-fluid">

                @include('admin.layouts.alerts')

                @yield('content')

            </div> <!-- container -->

        </div> <!-- content -->

        <!-- Footer Start -->
        <footer class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <script>document.write(new Date().getFullYear())</script> &copy; Mohada Back-office
                        Administrateur
                    </div>
                    <div class="col-md-6">
                        <div class="text-md-right footer-links d-none d-sm-block">
                            <a href="{{ route('index') }}" target="_blank">Home</a>
                            <a href="{{ route('investments') }}" target="_blank">Investments</a>
                            <a href="{{ route('services') }}" target="_blank">Services</a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- end Footer -->

    </div>

    <!-- ============================================================== -->
    <!-- End Page content -->
    <!-- ============================================================== -->


</div>
<!-- END wrapper -->

<!-- Vendor js -->
<script src="{{ asset('admin_assets/js/vendor.min.js') }}"></script>

<!-- Plugins js-->
<script src="{{ asset('admin_assets/libs/apexcharts/apexcharts.min.js') }}"></script>

<script src="{{ asset('admin_assets/libs/selectize/js/standalone/selectize.min.js') }}"></script>

<!-- App js-->
<script src="{{ asset('admin_assets/js/app.min.js') }}"></script>

{{-- Summernote --}}
<script src="{{ asset('admin_assets/js/summernote-bs4.min.js') }}"></script>

@yield('footer_script')
</body>
</html>

resources/views/admin/layouts/header.blade.php
<div class="navbar-custom">
    <div class="container-fluid">
        <ul class="list-unstyled topnav-menu float-right mb-0">


            <li class="dropdown d-none d-lg-inline-block">
                <a class="nav-link dropdown-toggle arrow-none waves-effect waves-light"
                   data-toggle="fullscreen"
                   href="#">
                    <i class="fe-maximize noti-icon"></i>
                </a>
            </li>

            <li class="dropdown notification-list topbar-dropdown">
                <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect waves-light" data-toggle="dropdown"
                   href="#" role="button" aria-haspopup="false" aria-expanded="false">
                    <img src="{{ asset('admin_assets/images/users/no-user.png') }}" alt="user-image"
                         class="rounded-circle">
                    <span class="pro-user-name ml-1">
                        {{ Auth('admin')->user()->name }} <i class="mdi mdi-chevron-down"></i>
                    </span>
                </a>
                <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                    <!-- item-->
                    <div class="dropdown-header noti-title">
                        <h6 class="text-overflow m-0">Welcome !</h6>
                    </div>

                    <!-- item-->
                    <a href="{{ route('admin.profile') }}" class="dropdown-item notify-item">
                        <i class="fe-settings"></i>
                        <span>Settings</span>
                    </a>

                    <div class="dropdown-divider"></div>

                    <!-- item-->
                    <a href="{{ route('admin.logout') }}" class="dropdown-item notify-item">
                        <i class="fe-log-out"></i>
                        <span>Logout</span>
                    </a>
                </div>
            </li>


        </ul>

        <!-- LOGO -->
        <div class="logo-box">
            <a href="{{ route('admin.dashboard') }}" class="logo logo-light text-center">
                    <span class="logo-sm">
                        <img src="{{ asset('images/logo_final-5.png') }}" alt="" height="22">
                    </span>
                <span class="logo-lg">
                        <img src="{{ asset('images/logo_final-5.png') }}" alt="" height="36">
                    </span>
            </a>
        </div>

        <ul class="list-unstyled topnav-menu topnav-menu-left m-0">
            <li>
                <button class="button-menu-mobile waves-effect waves-light">
                    <i class="fe-menu"></i>
                </button>
            </li>

            <li>
                <!-- Mobile menu toggle (Horizontal Layout)-->
                <a class="navbar-toggle nav-link" data-toggle="collapse" data-target="#topnav-menu-content">
                    <div class="lines">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </a>
                <!-- End mobile menu toggle-->
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>
</div>

resources/views/admin/layouts/sidebar.blade.php
<div class="left-side-menu">

    <div class="h-100" data-simplebar>

        <!--- Sidemenu -->
        <div id="sidebar-menu">

            <ul id="side-menu">

                <li class="menu-title">Navigation</li>

                <li class="{{ Route::is('admin.dashboard') ? 'menuitem-active' : '' }}">
                    <a href="{{ route('admin.dashboard') }}">
                        <i data-feather="airplay"></i>
                        <span> Dashboards </span>
                    </a>
                </li>

                <li class="menu-title mt-2">Projects</li>

                <li class="{{ (Request::is('admin/projects*') && 'pending' === Request::get('status')) ? 'menuitem-active' : '' }}">
                    <a href="{{ route('admin.projects.index', ['status' => 'pending']) }}" class="active">
                        <i data-feather="users"></i>
                        <span> Pending Review </span>
                    </a>
                </li>

                <li class="{{ (Request::is('admin/projects*') && 'pending' !== Request::get('status')) ? 'menuitem-active' : '' }}">
                    <a href="{{ route('admin.projects.index') }}">
                        <i data-feather="layers"></i>
                        <span> List </span>
                    </a>
                </li>

                <li class="{{ Request::is('admin/categories*') ? 'menuitem-active' : '' }}">
                    <a href="{{ route('admin.categories.index') }}">
                        <i data-feather="book-open"></i>
                        <span> Categories </span>
                    </a>
                </li>

                <li class="{{ Request::is('admin/countries*') ? 'menuitem-active' : '' }}">
                    <a href="{{ route('admin.countries.index') }}">
                        <i data-feather="globe"></i>
                        <span> Countries </span>
                    </a>
                </li>

                <li class="{{ Request::is('admin/blogs*') ? 'menuitem-active' : '' }}">
                    <a href="{{ route('admin.blogs.index') }}">
                        <i data-feather="bold"></i>
                        <span> Blogs </span>
                    </a>
                </li>

                <li class="{{ Request::is('admin/cities*') ? 'menuitem-active' : '' }}">
                    <a href="{{ route('admin.cities.index') }}">
                        <i data-feather="map-pin"></i>
                        <span> Cities </span>
                    </a>
                </li>

                <li class="{{ Request::is('admin/team*') ? 'menuitem-active' : '' }}">
                    <a href="{{ route('admin.team.index') }}">
                        <i class="mdi mdi-account-multiple"></i>
                        <span> Team </span>
                    </a>
                </li>

                <li class="{{ Request::is('admin/faqs*') ? 'menuitem-active' : '' }}">
                    <a href="{{ route('admin.faqs.index') }}">
                        <i data-feather="help-circle"></i>
                        <span> FAQs </span>
                    </a>
                </li>

            </ul>

        </div>
        <!-- End Sidebar -->

        <div class="clearfix"></div>

    </div>
    <!-- Sidebar -left -->

</div>