routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'PagesController@index')->name('index');

Auth::routes();

Route::post('/investments/invest/{id}', function (Request $request, $id) {
    try {
        \Mail::send(new \App\Mail\ProjectMail($request, $id, "reply"));
    } catch (Exception $err) {
    }
    return redirect('/')->with('toast_success', 'Thanks! Email sent to owner!');
})->name('invest');

Route::get('/investments', 'PagesController@investments')->name('investments');
Route::get('/investments/search', 'PagesController@search')->name('search');
Route::get('/investments/filter', 'PagesController@searchFilter')->name('filter');
Route::get('/investments/category/{category}', 'PagesController@searchCategory')->name('category');
Route::get('/investments/cities/{id}', 'PagesController@getCities')->name('cities');
Route::get('/investments/{id}', 'PagesController@details')->name('investments.show');
Route::get('/services', 'PagesController@services')->name('services');
Route::get('/services/details/{name}', 'PagesController@servicesDetails')->name('services-details');
Route::get('/about', 'PagesController@about')->name('about');
Route::get('/postproject', 'PagesController@postproject')->name('post');
Route::get('/help/show-more', 'PagesController@showMore')->name('help.showMore');
Route::get('/blog/{id}', 'PagesController@showblog')->name('blog.showblog');
Route::get('/help/searchblog', 'PagesController@searchblog')->name("searchblog");
Route::get('/help', 'PagesController@help')->name('help');
Route::get('/help/contact', 'PagesController@contact')->name('contact');
Route::get('/blog', 'PagesController@blog')->name('blog');
Route::post('/help/subscribe', 'MailChimpController@subscribe')->name('subscribe');

Route::resource('categories', 'CategoryController');
Route::resource('projects', 'ProjectController');
Route::get('/projects/image/{filename}', 'ProjectController@renderImage')->name('projects.image');
Route::post('/projects/store', 'ProjectController@store')->name('projects.store');

Route::get('blogs/image/{filename}', 'Admin\BlogController@renderImage')->name('posts.image');
Route::get('team/image/{filename}', 'Admin\TeamController@renderImage')->name('users.image');

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('login', 'Admin\Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Admin\Auth\LoginController@login')->name('login');

    Route::group(['middleware' => 'admin'], function () {
        Route::get('/', function () {
            return redirect()->route('admin.dashboard');
        });
        Route::get('dashboard', 'Admin\DashboardController@getDashboard')->name('dashboard');

        Route::resource('categories', 'Admin\CategoryController');

        Route::resource('countries', 'Admin\CountryController');
        Route::resource('team', 'Admin\TeamController');
        Route::resource('cities', 'Admin\CityController');
        Route::resource('faqs', 'Admin\FAQController');
        Route::PATCH('categories/{category}/restore', 'Admin\CategoryController@restore')->name('categories.restore');
        Route::PATCH('countries/{country}/restore', 'Admin\CountryController@restore')->name('countries.restore');

        Route::resource('blogs', 'Admin\BlogController');

        Route::resource('projects', 'Admin\ProjectController');
        Route::any('projects/{id}/{appraisal}', function ($id, $appraisal) {
            try {
                \Mail::send(new \App\Mail\ProjectMail(null, $id, $appraisal));
            } catch (Exception $err) {
            }
            return redirect('admin');
        })->name('appraisalMail');

        // PROFILE
        Route::get('/profile', 'Admin\ProfileController@getProfile')->name('profile');
        Route::post('/profile/edit', 'Admin\ProfileController@editProfile')->name('profile.edit');
        Route::post('/settings/edit', 'Admin\ProfileController@editSiteSettings')->name('settings.edit');
        Route::post('/profile/change-password', 'Admin\ProfileController@changePassword')->name('profile.password');

        Route::get('logout', 'Admin\Auth\LoginController@logout')->name('logout');
    });
});

app/Faq.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Faq extends Model
{
    //
}

app/Http/Controllers/Admin/FAQController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Faq;
use Illuminate\Support\Facades\Validator;

class FAQController extends Controller
{
    protected $search = [
        'voided' => false
    ];

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $this->search;
        $faqs = new faq();

        $faqs = $faqs->where('voided', false);

        if ($request->get('voided')) {
            $search['voided'] = $request->get('voided');
            $faqs = $faqs->orWhere('voided', true);
        }

        $faqs = $faqs->orderBy('created_at', 'desc')->get();
        return view('admin.faqs.index', compact('faqs', 'search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'question' => 'required|unique:faqs,question',
            'answer' => 'nullable'
        ]);

        $faq = new faq();
        $faq->question = $request->question;
        $faq->answer = $request->answer;
        $faq->save();

        return redirect()->route('admin.faqs.index')
            ->with('success', 'FAQ created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $faq = faq::findOrFail($id);
        return view('admin.faqs.edit', compact('faq'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $faq = faq::findOrFail($id);

        $validator = Validator::make($request->all(), [
            'question' => 'required',
            'answer' => 'nullable',
        ]);

        // Check to see if another faq already exist with the same name but different id
        $validator->after(function ($validator) use ($request, $faq) {
            $existing_cat = faq::where('question', $request->name)->first();
            if ($existing_cat && $existing_cat->id != $faq->id) {
                $validator->errors()->add('question', __('This question already exists'));
            }
        });

        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }


        $faq->question = $request->question;
        $faq->answer = $request->answer;
        $faq->save();

        return redirect()->route('admin.faqs.index')
            ->with('success', 'FAQ updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $faq = Faq::findOrFail($id);
        $faq->voided = true;
        $faq->save();

        return redirect()->route('admin.faqs.index')->with('success', 'FAQ deleted successfully');
    }

    public function restore($id)
    {
        $faq = Faq::findOrFail($id);
        $faq->voided = false;
        $faq->save();

        return redirect()->route('admin.faqs.index')->with('success', 'FAQ restored successfully');
    }
}

resources/views/admin/faqs/edit.blade.php
@extends('admin.layouts.app')
@section('title', $faq->question)

@section('content')
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('admin.faqs.index') }}">Categories</a></li>
                        <li class="breadcrumb-item active">{{ $faq->question }}</li>
                    </ol>
                </div>
                <h4 class="page-title">Edit: {{ $faq->question }}</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Edit FAQ</h5>
            <form method="POST" action="{{ route('admin.faqs.update', ['faq' => $faq->id]) }}">
                @csrf
                @method('PATCH')

                <div class="form-group">
                    <label>Question <em>*</em></label>
                    <input type="text" name="question"
                           value="{{ old('question', $faq->question) }}"
                           class="form-control @error('question') is-invalid @enderror">
                    @error('question')
                    <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>

                <div class="form-group">
                    <label>Answer</label>
                    <textarea class="form-control @error('answer') is-invalid @enderror"
                              name="answer" rows="5">{{ old('answer', $faq->answer) }}</textarea>
                    @error('answer')
                    <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>

                <div class="text-right">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>

            </form>
        </div>
    </div>

@endsection

@section('footer_script')
    <script></script>
@endsection

resources/views/admin/faqs/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Frequently Asked Questions')

@section('content')
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Dashboard</a></li>
                        <li class="breadcrumb-item active">Frequently Asked Questions</li>
                    </ol>
                </div>
                <h4 class="page-title">Frequently Asked Questions</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">FAQs</h5>
                    <div class="table-responsive">
                        <table class="table table-stripped">
                            <thead>
                            <tr>
                                <td>#</td>
                                <td>Questions</td>
                                <td>Answers</td>
                                <td>Action</td>
                            </tr>
                            </thead>
                            <tbody>
                                @forelse($faqs as $faq)
                                    @if(!$faq->voided)
                                        <tr>
                                            <td>{{ $loop->index + 1 }}</td>
                                            <td>{{ $faq->question }}</td>
                                            <td>{{ Str::limit($faq->answer, 10) }}</td>
                                            <td>
                                                <div class="btn-group">
                                                    <button class="btn btn-info btn-sm" title="view more"
                                                            data-toggle="modal" data-target="#view{{ $faq->id }}">
                                                        <i class="fa fa-eye"></i></button>
                                                    <a href="{{ route('admin.faqs.edit', ['faq' => $faq->id]) }}"
                                                    class="btn btn-light btn-sm" title="Edit"><i
                                                                class="fa fa-pen"></i></a>
                                                    <button class="btn btn-danger btn-sm" title="Delete" data-toggle="modal"
                                                            data-target="#delete{{ $faq->id }}">
                                                        <i class="fa fa-trash"></i></button>
                                                </div>
                                            </td>
                                        </tr>

                                        <div id="delete{{ $faq->id }}" class="modal fade" tabindex="-1" role="dialog"
                                            aria-hidden="true" style="display: none;">
                                            <div class="modal-dialog modal-sm">
                                                <div class="modal-content modal-filled bg-danger">
                                                    <div class="modal-body p-4">
                                                        <form method="POST"
                                                            action="{{ route('admin.faqs.destroy', ['faq' => $faq->id]) }}">
                                                            @method('DELETE')
                                                            @csrf
                                                            <div class="text-center">
                                                                <i class="dripicons-wrong h1 text-white"></i>
                                                                <h4 class="mt-2 text-white">Delete {{ $faq->question }}
                                                                    !</h4>
                                                                <p class="mt-3 text-white">
                                                                    Are you sure you want to delete this faq?
                                                                </p>
                                                                <button type="submit" class="btn btn-light my-2">Proceed
                                                                </button>
                                                            </div>
                                                        </form>
                                                    </div>
                                                </div><!-- /.modal-content -->
                                            </div><!-- /.modal-dialog -->
                                        </div>
                                    @else
                                        <tr class="text-muted">
                                            <td class="strike-through">{{ $loop->index + 1 }}</td>
                                            <td class="strike-through">{{ $faq->question }}</td>
                                            <td class="strike-through">{{ Str::limit($faq->answer, 10) }}</td>
                                            <td>
                                                <div class="btn-group">
                                                    <button class="btn btn-info btn-sm" title="view more"
                                                            data-toggle="modal" data-target="#view{{ $faq->id }}">
                                                        <i class="fa fa-eye"></i></button>
                                                    <button class="btn btn-light btn-sm" data-toggle="modal"
                                                            data-target="#restore{{ $faq->id }}">Restore
                                                    </button>
                                                </div>

                                            </td>
                                        </tr>

                                        <div id="restore{{ $faq->id }}" class="modal fade" tabindex="-1" role="dialog"
                                            aria-hidden="true" style="display: none;">
                                            <div class="modal-dialog modal-sm">
                                                <div class="modal-content modal-filled">
                                                    <div class="modal-body p-4">
                                                        <form method="POST"
                                                            action="{{ route('admin.faqs.restore', ['faq' => $faq->id]) }}">
                                                            @method('PATCH')
                                                            @csrf
                                                            <div class="text-center">
                                                                <i class="dripicons-warning h1 text-warning"></i>
                                                                <h4 class="mt-2 ">Restore {{ $faq->question }}
                                                                    !</h4>
                                                                <p class="mt-3">
                                                                    Are you sure you want to restore this faq?
                                                                </p>
                                                                <button type="submit" class="btn btn-warning my-2">Proceed
                                                                </button>
                                                            </div>
                                                        </form>
                                                    </div>
                                                </div><!-- /.modal-content -->
                                            </div><!-- /.modal-dialog -->
                                        </div>
                                    @endif

                                    <div class="modal fade" id="view{{ $faq->id }}" tabindex="-1" role="dialog"
                                        style="display: none;" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h4 class="modal-title" id="myCenterModalLabel">Details</h4>
                                                    <button type="button" class="close" data-dismiss="modal"
                                                            aria-hidden="true">×
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <h5>{{ $faq->question }}</h5>
                                                    <p>{{ $faq->answer ?: 'No Answer' }}</p>
                                                </div>
                                            </div><!-- /.modal-content -->
                                        </div><!-- /.modal-dialog -->
                                    </div>
                                @empty
                                    <tr>
                                        <td colspan="4" class="text-center">No Category Found</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                    <div class="text-right">
                        @if(!$search['voided'])
                            <a href="{{ route('admin.faqs.index', ['voided' => true]) }}"
                               class="small text-muted">Show deleted faqs</a>
                        @else
                            <a href="{{ route('admin.faqs.index') }}"
                               class="small text-muted">Hide deleted faqs</a>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">New FAQ</h5>
                    <form method="POST" action="{{ route('admin.faqs.store') }}">
                        @csrf

                        <div class="form-group">
                            <label>Question <em>*</em></label>
                            <input type="text" name="question"
                                   value="{{ old('question') }}"
                                   class="form-control @error('question') is-invalid @enderror">
                            @error('question')
                            <span class="invalid-feedback">{{ $message }}</span>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label>Answer</label>
                            <textarea class="form-control @error('answer') is-invalid @enderror"
                                      name="answer" rows="5">{{ old('answer') }}</textarea>
                            @error('answer')
                            <span class="invalid-feedback">{{ $message }}</span>
                            @enderror
                        </div>

                        <div class="text-right">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>


@endsection

@section('footer_script')
    <script></script>
@endsection